---
- hosts: localhost

  tasks:

  tasks:
    - name: Install the Terminal profile
      include_role:
        name: terminal

    - name: Install homebrew
      include_role:
        name: geerlingguy.mac.homebrew

    - name: Make sure homebrew bin is in path
      ansible.builtin.lineinfile:
        path: /etc/paths
        state: present
        line: '/opt/homebrew/bin'
      become: true
      become_user: root

    - name: 'add custom homebrew repos'
      community.general.homebrew_tap:
        name: [
          lucagrulla/tap
          hashicorp/tap
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      ignore_errors: yes
      with_items:
        - 1password
        - aws-vault
        - blackhole-2ch
        - docker
        - google-chrome
        - ngrok
        - slack
        - zoom
        - visual-studio-code

    - name: "Install homebrew packages"
      community.general.homebrew:
        name: [
          'autoconf',
          'automake',
          'coreutils',
          'curl',
          'cw',
          'dircolors',
          'elixir',
          'erlang',
          'ffmpeg',
          'flac',
          'gcc',
          'git',
          'gnutls',
          'jq',
          'libtool',
          'node',
          'openssl',
          'packer',
          'pkg',-'config',
          'postgresql@15',
          'sqlite',
          'terraform',
          'x264',
          'x265',
          'zlib',
        ]
        state: present
        update_homebrew: yes

    - name: "Install from Mac app store"
      shell: mas install {{ item }}
      with_items:
        - 497799835 # xcode

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: "/Users/{{ lookup('env', 'USER') }}/.oh-my-zsh"

    - name: "Create a default ZSH configuration"
      template:
        src: templates/.zshrc.j2
        dest: /Users/{{ lookup('env', 'USER') }}/.zshrc
        owner: "{{ lookup('env', 'USER') }}"
        force: yes

    - git:
        repo: https://github.com/asdf-vm/asdf.git
        dest: "/Users/{{ lookup('env', 'USER') }}/.asdf"
        version: v0.8.1

    - name: "Install asdf plugins"
      shell: |
        source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
        asdf plugin-add {{ item }} || exit 0
      with_items:
        - elixir
        - nodejs
        - erlang

    - name: "Install default node"
      shell: |
        source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
        asdf install nodejs 22.14.0
        asdf global nodejs 22.14.0

    - name: "Install default erlang"
      shell: |
        source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
        asdf install erlang 27.3.1
        asdf global erlang 27.3.1

    - name: "Install default elixir"
      shell: |
        source /Users/{{ lookup('env', 'USER') }}/.asdf/asdf.sh
        asdf install elixir 1.18.3
        asdf global elixir 1.18.3
        mix local.hex --force
